main: plugin.MineHunt.Main
name: MineHunt
version: 0.1.0
api-version: 1.17
author: Xuyuan

commands:
  cteam:
    description: Operate on teams
  cpoints:
    description: Alter team points
    aliases: [points]

permissions:
  minehunt.admin:
    description: Operate on MineHunt teams
    default: op